version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=finanzas_dev
      - POSTGRES_PASSWORD=1234
    networks:
      - postgresql
    volumes:
      - postgres:/var/lib/postgresql
networks:
  postgresql:

volumes:
  postgres: