spring:
  application:
    name: Finanzas
  config:
    import: optional:classpath:.env[.properties]
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/finanzas_dev
    password: '1234'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

nordigen:
  secret:
    id: ${nordigen.secret.id}
    key: ${nordigen.secret.key}